pipeline {
    agent {
       node {
         label "pkdev"
      }
    }
    stages {
        stage('Build') {
            steps {
                echo '<--------------- Building started --------------->'
                sh 'printenv'
                sh 'mvn clean install'
                echo '<------------- Build completed --------------->'
            }
        }

  stage ("Sonar Analysis") {
            environment {
               scannerHome = tool 'pkdev-SonarScanner'  //scanner name configured for slave 
            }
            steps {
                echo '<--------------- Sonar Analysis started  --------------->'
                withSonarQubeEnv('pkdev-SonarQube') {    
                    //sonarqube server name in master
                    sh "${scannerHome}/bin/sonar-scanner"
                }    
                echo '<--------------- Sonar Analysis stopped  --------------->'
            }   
        }
    }
}
